name: Check WebDAV Files
on: workflow_dispatch
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
      
      - name: Setup Config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: List ALL Files
        # lsf 命令列出文件，-a 代表显示隐藏文件，--format "ps" 显示路径和大小
        # 记得把 "6pan:备份" 改成你真实的路径
        run: rclone lsf "6pan:备份" -a --format "ps" -v
