name: Check WebDAV Files
on: workflow_dispatch
jobs:
  list-files:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rclone
        run: sudo -v ; curl https://rclone.org/install.sh | sudo bash
      
      - name: Setup Config
        run: |
          mkdir -p ~/.config/rclone
          echo "${{ secrets.RCLONE_CONF }}" | base64 -d > ~/.config/rclone/rclone.conf

      - name: List ALL Files
        # 修正：去掉了错误的 -a 参数
        # 增加了 --include ".*" 以确保显示以 . 开头的隐藏文件
        run: rclone lsf "6pan:备份" --format "ps" --include ".*" -v
